### ISSUE TITLE
mpv-nordlicht.lua: MPV 0.14.0 crashes sometimes when nordlicht starts generating a barcode

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#58]
With some files, MPV disappears after starting to play the file, but nordlicht keeps working.  The terminal is available.

A gdb output:

```
Program received signal SIGBUS, Bus error.
[Switching to Thread 0x7fffd51b0700 (LWP 5117)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33  ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) nordlicht: Building keyframe index... done.
nordlicht: 06%Terminated

(gdb) 
(gdb) 
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x00007fffc79436be in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007fffc7943ab2 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007fffc7944522 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fffc79357fb in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fffc7935a42 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#6  0x00007fffc7935e68 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#7  0x000055555563614c in glUploadTex (gl=0x7fffc021ca70, target=3553, format=6408, type=5121, dataptr=<optimized out>, stride=<optimized out>, 
    x=0, y=0, w=1920, h=96, slice=96) at ../video/out/opengl/utils.c:145
#8  0x0000555555634afa in upload_tex (osd=0x7fffc05b0290, imgs=0x7fffd51af890, imgs=0x7fffd51af890, ctx=0x7fffc05b4a80)
    at ../video/out/opengl/osd.c:221
#9  upload_osd (imgs=0x7fffd51af890, osd=0x7fffc05b0290, ctx=0x7fffc05b4a80) at ../video/out/opengl/osd.c:272
#10 gen_osd_cb (pctx=pctx@entry=0x7fffc05b4a80, imgs=imgs@entry=0x7fffd51af890) at ../video/out/opengl/osd.c:289
#11 0x0000555555615dd5 in osd_draw (osd=0x555555959ba0, res=..., video_pts=0.16700000000000001, draw_flags=0, 
    formats=formats@entry=0x7fffc05b4ad0, cb=cb@entry=0x5555556348d0 <gen_osd_cb>, cb_ctx=cb_ctx@entry=0x7fffc05b4a80) at ../sub/osd.c:331
#12 0x0000555555635741 in mpgl_osd_generate (ctx=0x7fffc05b4a80, res=..., pts=<optimized out>, stereo_mode=0, draw_flags=<optimized out>)
    at ../video/out/opengl/osd.c:424
#13 0x000055555563919f in pass_draw_osd (p=p@entry=0x7fffc042c500, draw_flags=<optimized out>, pts=<optimized out>, rect=..., vp_w=1920, 
    vp_h=-1080, fbo=fbo@entry=0, cms=cms@entry=true) at ../video/out/opengl/video.c:1812
#14 0x000055555563e340 in gl_video_render_frame (p=0x7fffc042c500, frame=frame@entry=0x7fffc200b6b0, fbo=fbo@entry=0)
    at ../video/out/opengl/video.c:2213
#15 0x0000555555646664 in draw_frame (vo=<optimized out>, frame=0x7fffc200b6b0) at ../video/out/vo_opengl.c:138
#16 0x000055555564398e in render_frame (vo=0x55555597e6f0) at ../video/out/vo.c:808
#17 vo_thread (ptr=0x55555597e6f0) at ../video/out/vo.c:905
#18 0x00007ffff494e284 in start_thread (arg=0x7fffd51b0700) at pthread_create.c:333
#19 0x00007fffefd5ea4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

```
$ mpv --version
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6-1+b1
```

**Comment by rohieb** [comment]
Huh. That looks like a bug in mpv itself or the graphics driver to me. It _could_ be that mpv is trying to read the bgra overlay, which doesn't exist yet… let me just check that.

**Comment by rohieb** [comment]
Right, there was some variable confusion going on, which were fixed in 7b6fcd6. @aleksejrs, can you confirm that it works in 7b6fcd6?

**Comment by blinry** [comment]
I'm also getting this error on the current nordlicht master, with mpv 0.16.0 and an unsuspicious mp4 file:

```
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isom
    creation_time   : 2015-07-02 03:16:24
  Duration: 00:46:32.11, start: 0.000000, bitrate: 637 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 131 kb/s (default)
    Metadata:
      creation_time   : 2015-07-02 03:16:24
      handler_name    : GPAC ISO Audio Handler
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown), 720x404, 502 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2015-07-02 02:28:40
      handler_name    : L-SMASH Video Media Handler
      encoder         : AVC Coding
```

Will also investigate further...

**Comment by aleksejrs** [comment]
> Right, there was some variable confusion going on, which were fixed in 7b6fcd6. @aleksejrs, can you confirm that it works in 7b6fcd6?

It's the same version.

**Comment by blinry** [comment]
I'm working on a rewrite of mpv-nordlicht.lua, with proper threads using [luaposix](https://github.com/luaposix/luaposix), which should fix problems like this. I'm aware that we'll lose Windows compability, but this integration is so niche that I don't think anyone will care. :-P

**Comment by aleksejrs** [comment]
>  I'm aware that we'll lose Windows compability

If it still works, why not leave the old version there, too?

**Comment by blinry** [comment]
This crash should™ not happen in the new mpv-nordlicht version using luaposix.

@aleksejrs, are you using Windows yourself? We could link to the old version of the script in the version history, but the new version is so much superior to the old one that it doesn't seem sensible to me to maintain both.

**Comment by aleksejrs** [comment]
> @aleksejrs, are you using Windows yourself?

No. OK.
